language: android
android:
  components:
    - tools
    - build-tools-28.0.13
    - android-28
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

sudo: required

jdk:
  - oraclejdk8

install: true

before_script:
  - chmod +x gradlew

script:
 - chmod +x ./gradlew
