language: android
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - platform-tools
    - extra-android-support # because I'm use support library
    - extra-android-m2repository # because I'm use support library
  licenses:
    - '.+'
