language: android
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'
