language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    
before_install:
  - yes | sdkmanager "platforms;android-28"
